#app.upload.dir=${maven.basedir}/src/main/resources/static/files
app:
  upload:
    dir: @project.basedir@/src/main/resources/static/img

spring:
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://worker.local:3306/springbootdemoproject?createDatabaseIfNotExist=true
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false



server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-exception: true

logging:
  level:
    root: INFO
    com.instructor.springbootdemoproject: INFO
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql: INFO
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
server:
  port: 9000
spring:
  config:
    activate:
      on-profile: test